title: Fridge Dev Blog
author:
  repo: https://github.com/fridge-dev/blog
  name: fridge-dev
  email: fridgedevblog@gmail.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  This is a software engineering blog covering my interests and ways of thinking about
  various topics of being an IC or IC leader in a software engineering org.
  Iâ€™m interested in problem solving, code understandability, design patterns,
  code architecture, system architecture, large scale failure modes, distributed
  systems algorithms, teaching, learning how other people think, figuring out how
  to make complex systems easier for others to understand, and being a leader.

disclaimer: The opinions on this site are my own. They do not necessarily represent those of my employer.

# Build settings

# As of November 2023, GitHub Pages still uses Minima 2.5.1 (https://pages.github.com/versions/).
# To use minima v3, we use remote theme
#theme: minima
remote_theme: jekyll/minima

plugins:
  # From minima v3:
  - jekyll-seo-tag
  # Gen AI prompt: "github pages how to redirect from one markdown file to another"
  - jekyll-redirect-from

# Theme-specific settings

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages:
  - about.md

# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  # Minima skin selection.
  # Available skins are:
  # classic            Default, light color scheme.
  # dark               Dark variant of the classic skin.
  # auto               Adaptive skin based on the default classic and dark skins.
  # solarized-light    Light variant of solarized color scheme.
  # solarized-dark     Dark variant of solarized color scheme.
  # solarized          Adaptive skin for solarized color scheme skins.
  skin: solarized
